In [3]:
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix, accuracy_score

# Dataset as a dictionary
data = {
    "Gender": ["male", "male", "male", "male", "female", "female", "female", "female"],
    "Height": [6.00, 5.92, 5.58, 5.92, 5.00, 5.50, 5.42, 5.75],
    "Weight": [180, 190, 170, 165, 100, 150, 130, 150],
    "Foot_Size": [12, 11, 12, 10, 6, 8, 7, 9],
    "Label": ["male", "male", "male", "male", "female", "female", "female", "female"]
}

# Constructing a Pandas DataFrame
df = pd.DataFrame(data)

# Encoding categorical labels (Gender and Label) into numerical values
df["Gender"] = df["Gender"].map({"male": 1, "female": 0})
df["Label"] = df["Label"].map({"male": 1, "female": 0})

# Features (Height, Weight, Foot_Size) and Labels
features = df[["Height", "Weight", "Foot_Size"]].values
labels = df["Label"].values

# Decision Tree Classifier
classifier = DecisionTreeClassifier()

# Train the model
classifier = classifier.fit(features, labels)

# New entry
new_entry = [[6.00, 180, 12]]  # Height, Weight, Foot_Size

# Predict the class of the new entry
prediction = classifier.predict(new_entry)
predicted_class = "male" if prediction[0] == 1 else "female"
print(f"Prediction for the new entry {new_entry}: {predicted_class}")

# Testing Confusion Matrix and Accuracy (using the training data itself)
predicted_labels = classifier.predict(features)
conf_mat = confusion_matrix(labels, predicted_labels)
accuracy = accuracy_score(labels, predicted_labels)

# Print Confusion Matrix and Accuracy
print("\nConfusion Matrix:")
print(conf_mat)
print(f"\nAccuracy: {accuracy * 100:.2f}%")


Prediction for the new entry [[6.0, 180, 12]]: male

Confusion Matrix:
[[4 0]
 [0 4]]

Accuracy: 100.00%


In [9]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix, accuracy_score

# Original Dataset as a dictionary
data = {
    "Gender": ["male", "male", "male", "male", "female", "female", "female", "female"],
    "Height": [6.00, 5.92, 5.58, 5.92, 5.00, 5.50, 5.42, 5.75],
    "Weight": [180, 190, 170, 165, 100, 150, 130, 150],
    "Foot_Size": [12, 11, 12, 10, 6, 8, 7, 9],
    "Label": ["male", "male", "male", "male", "female", "female", "female", "female"]
}

# Constructing a Pandas DataFrame
df = pd.DataFrame(data)

# Encoding categorical labels (Gender and Label) into numerical values
df["Gender"] = df["Gender"].map({"male": 1, "female": 0})
df["Label"] = df["Label"].map({"male": 1, "female": 0})

# Features and Labels
features = df[["Height", "Weight", "Foot_Size"]].values
labels = df["Label"].values

# Decision Tree Classifier
classifier = DecisionTreeClassifier()
classifier.fit(features, labels)

# New entry
new_entry = [6.00, 180, 12]

# Predict class for the new entry
new_label = classifier.predict([new_entry])[0]
predicted_class = "male" if new_label == 1 else "female"
print(f"Prediction for the new entry {new_entry}: {predicted_class}")

# Add new entry to the dataset
df = df.append({"Height": new_entry[0], "Weight": new_entry[1], "Foot_Size": new_entry[2], "Label": new_label}, ignore_index=True)

# Retrain the classifier with the updated dataset
features = df[["Height", "Weight", "Foot_Size"]].values
labels = df["Label"].values
classifier = classifier.fit(features, labels)

# Confusion Matrix and Accuracy
predicted_labels = classifier.predict(features)
conf_mat = confusion_matrix(labels, predicted_labels)
accuracy = accuracy_score(labels, predicted_labels)

print("\nUpdated Dataset:")
print(df)
print("\nConfusion Matrix:")
print(conf_mat)
print(f"\nAccuracy: {accuracy * 100:.2f}%")


Prediction for the new entry [6.0, 180, 12]: male


AttributeError: 'DataFrame' object has no attribute 'append'

In [10]:
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix, accuracy_score

# Original Dataset
features = np.array([
    [6.00, 180, 12],
    [5.92, 190, 11],
    [5.58, 170, 12],
    [5.92, 165, 10],
    [5.00, 100, 6],
    [5.50, 150, 8],
    [5.42, 130, 7],
    [5.75, 150, 9]
])
labels = np.array([1, 1, 1, 1, 0, 0, 0, 0])  # 1: male, 0: female

# Train the Decision Tree Classifier
classifier = DecisionTreeClassifier()
classifier.fit(features, labels)

# New entry
new_entry = np.array([[6.00, 180, 12]])

# Predict the class for the new entry
new_label = classifier.predict(new_entry)[0]
predicted_class = "male" if new_label == 1 else "female"
print(f"Prediction for the new entry {new_entry}: {predicted_class}")

# Add new entry to the dataset
features = np.vstack([features, new_entry])
labels = np.append(labels, new_label)

# Retrain the classifier with the updated dataset
classifier.fit(features, labels)

# Confusion Matrix and Accuracy
predicted_labels = classifier.predict(features)
conf_mat = confusion_matrix(labels, predicted_labels)
accuracy = accuracy_score(labels, predicted_labels)

print("\nUpdated Dataset Features:")
print(features)
print("\nUpdated Dataset Labels:")
print(labels)
print("\nConfusion Matrix:")
print(conf_mat)
print(f"\nAccuracy: {accuracy * 100:.2f}%")


Prediction for the new entry [[  6. 180.  12.]]: male

Updated Dataset Features:
[[  6.   180.    12.  ]
 [  5.92 190.    11.  ]
 [  5.58 170.    12.  ]
 [  5.92 165.    10.  ]
 [  5.   100.     6.  ]
 [  5.5  150.     8.  ]
 [  5.42 130.     7.  ]
 [  5.75 150.     9.  ]
 [  6.   180.    12.  ]]

Updated Dataset Labels:
[1 1 1 1 0 0 0 0 1]

Confusion Matrix:
[[4 0]
 [0 5]]

Accuracy: 100.00%
